library(shiny)
library(activityinfo)
library(bslib)
library(gridlayout)
library(DT)
library(waiter)
library(readxl)
library(writexl)
library(purrr)
source("global.R")
source("R/QAFromAIDB.R")
source("ui.R")
source("server.R")
shinyApp(ui = ui, server = server)